### ISSUE TITLE
Seafile webdav problem

### ISSUE THREAD

**Issue by gerickt** [Zimbra-Community/owncloud-zimlet#127]
Hi guys, a try to configure owncloud.zimlet whit Seafile server.
my config file /opt/zimbra/lib/ext/ownCloud/config.properties    
```
#Updated by installer via propmigr.
#Thu Mar 23 16:41:00 BOT 2017
owncloud_zimlet_disable_ocs_public_link_shares=false
owncloud_zimlet_disable_rename_delete_new_folder=false
owncloud_zimlet_default_folder=
owncloud_zimlet_extra_toolbar_button_url=/owncloud
owncloud_zimlet_server_port=
owncloud_zimlet_oc_folder=/owncloud
owncloud_zimlet_server_path=192.168.1.222/seafdav/
owncloud_zimlet_preview_delay=200
owncloud_zimlet_max_upload_size=104857600
owncloud_zimlet_extra_toolbar_button_title=Open ownCloud tab
owncloud_zimlet_welcome_url=https\://barrydegraaff.github.io/owncloud/
owncloud_zimlet_ask_folder_each_time=false
owncloud_zimlet_app_title=Seafile
owncloud_zimlet_server_name=
allowdomains=*
file_number=1000000
disable_password_storing=false
owncloud_zimlet_use_numbers=false
```
then configure account, whit:
CalDAV Server: https://192.168.1.222
Port: 8080
DAV path: /seafdav
location: empty
default folder: empty

the error: DAV ERRROR, no route to host

**Comment by barrydegraaff** [comment]
try:
owncloud_zimlet_server_name=https://192.168.1.222
owncloud_zimlet_server_path=/seafdav/

The error you are getting, suggest you forgot https:// or something like that.

Also try a fresh account, to make sure it is not a cache issue.

Barry

**Comment by gerickt** [comment]
thanks, that solve.. now i have a issue with ssl (server for testing without certificates)
> Unable to find valid certification path to requested target

solved follow: https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Troubleshooting#zal-soap-unknown-exception-javaxnetsslsslprotocolexception-handshake-alert-unrecognized_name

commands:
obtain certificate
`openssl s_client -connect 192.168.1.222:443 | tee logfile`
copy from -- BEGIN to END -- into a file, then:
`openssl s_client -connect 192.168.1.222:443 | tee logfile`
finally import into zimbra
`/opt/zimbra/common/bin/keytool -import -alias new2 -keystore /opt/zimbra/common/etc/java/cacerts -storepass changeit -file seafile.crt `
restart mailbox
`zmmailboxdctl restart`

in web zimbra interface... no show errors, but files tab is empty... 
only show "Loading..."
any clue?

**Comment by barrydegraaff** [comment]
tail -f /opt/zimbra/log/*

and then try again.

**Comment by gerickt** [comment]
i got this
```
==> /opt/zimbra/log/mailbox.log <==
2017-03-24 10:51:12,380 WARN  [qtp60830820-240:https:https://192.168.1.252:8443/service/soap/davSoapConnector] [name=gerick@lab.bo;mid=11;ip=192.168.1.50;port=42638;ua=ZimbraWebClient - FF52 (Linux)/8.7.2_GA_1736;] SoapEngine - handler exception
java.lang.NullPointerException
	at com.github.sardine.DavResource.getCustomProps(DavResource.java:524)
	at com.zextras.dav.DavSoapConnector.propfind(DavSoapConnector.java:237)
	at com.zextras.dav.DavSOAPHandler.handleRequest(DavSOAPHandler.java:141)
	at org.openzal.zal.soap.InternalDocumentHelper.handle(InternalDocumentHelper.java:75)
	at org.openzal.zal.soap.InternalDocumentHandler.handle(InternalDocumentHandler.java:42)
	at com.zimbra.soap.SoapEngine.dispatchRequest(SoapEngine.java:605)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:458)
	at com.zimbra.soap.SoapEngine.dispatch(SoapEngine.java:271)
	at com.zimbra.soap.SoapServlet.doWork(SoapServlet.java:303)
	at com.zimbra.soap.SoapServlet.doPost(SoapServlet.java:213)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at com.zimbra.cs.servlet.ZimbraServlet.service(ZimbraServlet.java:206)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at com.zimbra.cs.servlet.CsrfFilter.doFilter(CsrfFilter.java:169)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter(ETagHeaderFilter.java:47)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter(ZimbraInvalidLoginFilter.java:117)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:473)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:318)
	at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:288)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:318)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
	at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:84)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
2017-03-24 10:51:12,382 INFO  [qtp60830820-240:https:https://192.168.1.252:8443/service/soap/davSoapConnector] [name=gerick@lab.bo;mid=11;ip=192.168.1.50;port=42638;ua=ZimbraWebClient - FF52 (Linux)/8.7.2_GA_1736;] soap - davSoapConnector elapsed=78

==> /opt/zimbra/log/trace_log.2017_03_24 <==
10:51:12.382:qtp60830820-240:https:https://192.168.1.252:8443/service/soap/davSoapConnector RESPONSE 500 text/javascript; charset=utf-8

==> /opt/zimbra/log/access_log.2017-03-24 <==
192.168.1.50 - - [24/mar/2017:14:51:12 +0000] "POST https://192.168.1.252:8443/service/soap/davSoapConnector HTTP/1.1" 500 375 "https://192.168.1.252:8443/?adminPreAuth=1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" 81
```

**Comment by barrydegraaff** [comment]
That means you need to set a value for one of the preferences,
that you left blank at the moment.

Maybe
owncloud_zimlet_oc_folder  (set it to /owncloud, even if you do not use it)

also to that for default folder and all other fields, even if you do use them.


Its a bug- if we can figure out what the required field is, we can work around it
for now.

**Comment by gerickt** [comment]
does not work :(

**Comment by barrydegraaff** [comment]
can you provide me with a test account? You can send it to info at barrydegraaff dot tk

**Comment by gerickt** [comment]
It's a lab, I do not have it published.

**Comment by barrydegraaff** [comment]
Have no way to debug this, so closing.

**Comment by fr500** [comment]
I can provide such an account

**Comment by barrydegraaff** [comment]
You can send the details to info@barrydegraaff.tk

I need the seafile account more than the zimbra one.
