### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by lsenecaux** [Zimbra-Community/owncloud-zimlet#142]
ZCS version: 8.6.0_P6
OS version: CentOS 6.4

I had an issue when I try to install it on my zcs.
I have a multi-server installation (2 LDAP + 1 store + 2 proxy and no zimbra MTA)

Remove old versions of Zimlet.
[] INFO: Uninstalling Zimlet tk_barrydegraaff_owncloud_zimlet from LDAP.
[] INFO: undeploying zimlet tk_barrydegraaff_owncloud_zimlet
[] INFO: zimlet directory tk_barrydegraaff_owncloud_zimlet is deleted
[] INFO: Undeploying on vzimbra-ldap-1.espe-lnf.fr
[] INFO: ui node vzimbra-ldap-1.espe-lnf.fr is on version pre 8.5, aborting
[] INFO: Undeploying on vzimbra-ldap-2.espe-lnf.fr
[] WARN: undeployment failed on ui node vzimbra-ldap-2.espe-lnf.fr
com.zimbra.common.service.ServiceException: invalid request: server vzimbra-ldap-2.espe-lnf.fr does not have zimbraMailMode set, maybe it is not a store server?
ExceptionId:main:1506060422290:292fff9c1a44c1c6
Code:service.INVALID_REQUEST
        at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:267)
        at com.zimbra.cs.httpclient.URLUtil.getServiceURL(URLUtil.java:186)
        at com.zimbra.cs.util.WebClientServiceUtil.sendUndeployZimletRequestToUiNode(WebClientServiceUtil.java:281)
        at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.undeployZimletOnUiNode(ZimletUtil.java:1635)
        at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.undeployZimletRemotely(ZimletUtil.java:1486)
        at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletRemotely(ZimletUtil.java:1249)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1886)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)
com.zimbra.common.service.ServiceException: invalid request: server vzimbra-ldap-2.espe-lnf.fr does not have zimbraMailMode set, maybe it is not a store server?
ExceptionId:main:1506060422290:292fff9c1a44c1c6
Code:service.INVALID_REQUEST
        at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:267)
        at com.zimbra.cs.httpclient.URLUtil.getServiceURL(URLUtil.java:186)
        at com.zimbra.cs.util.WebClientServiceUtil.sendUndeployZimletRequestToUiNode(WebClientServiceUtil.java:281)
        at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.undeployZimletOnUiNode(ZimletUtil.java:1635)
        at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.undeployZimletRemotely(ZimletUtil.java:1486)
        at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletRemotely(ZimletUtil.java:1249)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1886)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)
[] ERROR: Error
com.zimbra.common.service.ServiceException: invalid request: server vzimbra-ldap-2.espe-lnf.fr does not have zimbraMailMode set, maybe it is not a store server?
ExceptionId:main:1506060422290:292fff9c1a44c1c6
Code:service.INVALID_REQUEST
        at com.zimbra.common.service.ServiceException.INVALID_REQUEST(ServiceException.java:267)
        at com.zimbra.cs.httpclient.URLUtil.getServiceURL(URLUtil.java:186)
        at com.zimbra.cs.util.WebClientServiceUtil.sendUndeployZimletRequestToUiNode(WebClientServiceUtil.java:281)
        at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.undeployZimletOnUiNode(ZimletUtil.java:1635)
        at com.zimbra.cs.zimlet.ZimletUtil$ZimletSoapUtil.undeployZimletRemotely(ZimletUtil.java:1486)
        at com.zimbra.cs.zimlet.ZimletUtil.undeployZimletRemotely(ZimletUtil.java:1249)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1886)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1973)

**Comment by barrydegraaff** [comment]
Hello,

The installer halts on errors, 

Try to uncomment line 22 and see if the installer proceeds.
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/webdav-client-installer.sh#L22

Regards, Barry

**Comment by lsenecaux** [comment]
No, it fails.
But it proceeds if I answer "No" to 'Do you want to automatically install Zimlet and force enable it in all COS ?'
But, after modify config.properties, I had a new issue :

java -jar prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/config_template.xml
java.io.FileNotFoundException: /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/config_template.xml (Aucun fichier ou dossier de ce type)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
        at java.io.PrintWriter.<init>(PrintWriter.java:184)
        at tk.barrydegraaff.prop2xml.main(prop2xml.java:21)

**Comment by barrydegraaff** [comment]
Yah, that is because that command is used when you did Y for deploy automatically. 


java -jar prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties config_template.xml 


You should point it to the correct location of config_template.xml. 


You can extract it from the Zimlet and store it back: 
https://wiki.zimbra.com/wiki/Zimlets,_Setting_Up#How_to_Change_Zimlet_Configurations 

In between run the prop2xml. 


Kind regards, 

Barry de Graaff 
Zeta Alliance Founder 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by lsenecaux** [comment]
Right, it installs.

However, I use, for ZCS, an SSO Authentication with CAS (https://github.com/apereo/cas).
Is your roadmap will include a such authentication for this zimlet ?

Regards,

**Comment by barrydegraaff** [comment]
Probably not, as I have no funding for it, and it will be expensive. 

Also, a limiting factor is, that a number of my important users, use this 
Zimlet combined with Windows Network drives (Nextcloud external storage). 
Then the password is passed on to Windows, so the proper rights can be 
applied. 

I could do SSO with SAML to Nextcloud, but then there is no option to have 
Nextcloud authenticate to Windows. 

There is also Zimbra Drive... in 8.8 Network edition or 8.7 FOSS, that allows 
to install an app in Nextcloud to do the authentication, but they have some issues 
in supporting the latest nextcloud. 

Kind regards, 

Barry de Graaff 
Zeta Alliance Founder 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by lsenecaux** [comment]
Thanks for your answer,

regards
