### ISSUE TITLE
Error when install zimlet

### ISSUE THREAD

**Issue by leo-yip** [Zimbra-Community/owncloud-zimlet#62]
Deploying zimlet...
[] INFO: Deploying Zimlet tk_barrydegraaff_owncloud_zimlet in LDAP.
[] INFO: Installing Zimlet tk_barrydegraaff_owncloud_zimlet on this host.
[] INFO: Upgrading Zimlet tk_barrydegraaff_owncloud_zimlet to 0.2.0
[] WARN: Problem parsing XML - Fatal Error: Problem on line -1 of document : Premature end of file.
com.zimbra.cs.zimlet.ZimletException: Cannot parse Zimlet description: Document parse failed
        at com.zimbra.cs.zimlet.ZimletException.INVALID_ZIMLET_DESCRIPTION(ZimletException.java:40)
        at com.zimbra.cs.zimlet.ZimletMeta.<init>(ZimletMeta.java:66)
        at com.zimbra.cs.zimlet.ZimletConfig.<init>(ZimletConfig.java:44)
        at com.zimbra.cs.zimlet.ZimletFile.initZimletConfig(ZimletFile.java:292)
        at com.zimbra.cs.zimlet.ZimletFile.getZimletConfig(ZimletFile.java:314)
        at com.zimbra.cs.zimlet.ZimletUtil.deployZimletLocally(ZimletUtil.java:632)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1883)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1985)
[] ERROR: Error
com.zimbra.cs.zimlet.ZimletException: Cannot parse Zimlet description: Document parse failed
        at com.zimbra.cs.zimlet.ZimletException.INVALID_ZIMLET_DESCRIPTION(ZimletException.java:40)
        at com.zimbra.cs.zimlet.ZimletMeta.<init>(ZimletMeta.java:66)
        at com.zimbra.cs.zimlet.ZimletConfig.<init>(ZimletConfig.java:44)
        at com.zimbra.cs.zimlet.ZimletFile.initZimletConfig(ZimletFile.java:292)
        at com.zimbra.cs.zimlet.ZimletFile.getZimletConfig(ZimletFile.java:314)
        at com.zimbra.cs.zimlet.ZimletUtil.deployZimletLocally(ZimletUtil.java:632)
        at com.zimbra.cs.zimlet.ZimletUtil.dispatch(ZimletUtil.java:1883)
        at com.zimbra.cs.zimlet.ZimletUtil.main(ZimletUtil.java:1985)

  Extension jar and zimlet deployed, restart your mailbox server to load the extension.

**Comment by barrydegraaff** [comment]
I have seen this error often as well,

I am not really sure why, but it seems like Zimbra tries to read something,
but it is not on the storage yet.

**Re-do the ./install and then it always works.**

Unfortunately I reported some of the issues around this, but Zimbra marked those
as invalid.

This is why for all my other projects I deploy in _dev.... maybe I should do that
for this Zimlet as well, as I am already getting loads of this reports.

Also not enabling the zimlet, or not putting it in the cos, seems to happen
more in 8.7.

@bud-mo : Since this is the 4th report this week about the zimlet not properly deploying, I would like to start and deploy in _dev folder once again.

**Comment by barrydegraaff** [comment]
Added simplified installer:
https://github.com/Zimbra-Community/owncloud-zimlet

It would have taken care of these issues.
